const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('astra', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: settings => ipcRenderer.invoke('settings:save', settings),
  getDiagnostics: () => ipcRenderer.invoke('diagnostics:get'),
  exportDiagnostics: () => ipcRenderer.invoke('diagnostics:export'),
  restartSafeMode: () => ipcRenderer.invoke('app:restart-safe-mode'),
  restartNormalMode: () => ipcRenderer.invoke('app:restart-normal-mode'),
  sendChat: payload => ipcRenderer.invoke('chat:send', payload),
  startChatStream: payload => ipcRenderer.invoke('chat:stream-start', payload),
  stopChatStream: requestId => ipcRenderer.invoke('chat:stream-stop', requestId),
  getLocalAi: () => ipcRenderer.invoke('local-ai:get'),
  saveLocalAi: payload => ipcRenderer.invoke('local-ai:save', payload),
  selectLocalAiRuntime: () => ipcRenderer.invoke('local-ai:select-runtime'),
  selectLocalAiModel: () => ipcRenderer.invoke('local-ai:select-model'),
  selectLocalAiMmproj: () => ipcRenderer.invoke('local-ai:select-mmproj'),
  startLocalAi: () => ipcRenderer.invoke('local-ai:start'),
  stopLocalAi: () => ipcRenderer.invoke('local-ai:stop'),
  dismissLocalAiWizard: () => ipcRenderer.invoke('local-ai:wizard-dismiss'),
  downloadManagedModel: modelId => ipcRenderer.invoke('model-manager:download', modelId),
  selectManagedModel: modelId => ipcRenderer.invoke('model-manager:select', modelId),
  pauseManagedModelDownload: () => ipcRenderer.invoke('model-manager:pause'),
  resumeManagedModelDownload: modelId => ipcRenderer.invoke('model-manager:resume', modelId),
  cancelManagedModelDownload: modelId => ipcRenderer.invoke('model-manager:cancel', modelId),
  inspectLocalAiModel: () => ipcRenderer.invoke('model-manager:inspect'),
  openLocalAiModelDirectory: () => ipcRenderer.invoke('model-manager:open-directory'),
  deleteManagedModel: modelId => ipcRenderer.invoke('model-manager:delete', modelId),
  getOfflineVoice: () => ipcRenderer.invoke('offline-voice:get'),
  saveOfflineVoice: payload => ipcRenderer.invoke('offline-voice:save', payload),
  selectOfflineVoiceRuntime: () => ipcRenderer.invoke('offline-voice:select-runtime'),
  selectOfflineVoiceModel: () => ipcRenderer.invoke('offline-voice:select-model'),
  transcribeOfflineAudio: payload => ipcRenderer.invoke('offline-voice:transcribe', payload),
  getKnowledge: () => ipcRenderer.invoke('knowledge:get'),
  importKnowledge: () => ipcRenderer.invoke('knowledge:import'),
  removeKnowledge: id => ipcRenderer.invoke('knowledge:remove', id),
  clearKnowledge: () => ipcRenderer.invoke('knowledge:clear'),
  searchKnowledge: query => ipcRenderer.invoke('knowledge:search', query),
  getScenario: () => ipcRenderer.invoke('scenario:get'),
  setScenario: id => ipcRenderer.invoke('scenario:set', id),
  saveScenario: payload => ipcRenderer.invoke('scenario:save', payload),
  getWorkflows: () => ipcRenderer.invoke('workflows:get'),
  addWorkflow: payload => ipcRenderer.invoke('workflows:add', payload),
  removeWorkflow: id => ipcRenderer.invoke('workflows:remove', id),
  runWorkflow: (id, confirmed) => ipcRenderer.invoke('workflows:run', { id, confirmed }),
  getFocus: () => ipcRenderer.invoke('focus:get'),
  startFocus: payload => ipcRenderer.invoke('focus:start', payload),
  stopFocus: () => ipcRenderer.invoke('focus:stop'),
  saveFocusSettings: payload => ipcRenderer.invoke('focus:save-settings', payload),
  clearFocusHistory: () => ipcRenderer.invoke('focus:clear-history'),
  exportLocalData: () => ipcRenderer.invoke('data:export'),
  importLocalData: () => ipcRenderer.invoke('data:import'),
  clearLocalData: () => ipcRenderer.invoke('data:clear'),
  completeOnboarding: () => ipcRenderer.invoke('app:complete-onboarding'),
  checkForUpdates: () => ipcRenderer.invoke('app:check-updates'),
  getMemory: () => ipcRenderer.invoke('memory:get'),
  addMemory: memory => ipcRenderer.invoke('memory:add', memory),
  updateMemory: (id, patch) => ipcRenderer.invoke('memory:update', { id, patch }),
  removeMemory: id => ipcRenderer.invoke('memory:remove', id),
  clearMemory: () => ipcRenderer.invoke('memory:clear'),
  saveMemoryProfile: profile => ipcRenderer.invoke('memory:save-profile', profile),
  getCompanion: () => ipcRenderer.invoke('companion:get'),
  saveCompanionSettings: settings => ipcRenderer.invoke('companion:save-settings', settings),
  recordCompanionEvent: event => ipcRenderer.invoke('companion:record-event', event),
  resetCompanion: () => ipcRenderer.invoke('companion:reset'),
  getPlanner: () => ipcRenderer.invoke('planner:get'),
  addTask: task => ipcRenderer.invoke('planner:add-task', task),
  updateTask: (id, patch) => ipcRenderer.invoke('planner:update-task', { id, patch }),
  removeTask: id => ipcRenderer.invoke('planner:remove-task', id),
  addPlannerReminder: reminder => ipcRenderer.invoke('planner:add-reminder', reminder),
  cancelPlannerReminder: id => ipcRenderer.invoke('planner:cancel-reminder', id),
  saveProactiveSettings: settings => ipcRenderer.invoke('planner:save-settings', settings),
  getDailySummary: () => ipcRenderer.invoke('planner:summary'),
  transcribeAudio: payload => ipcRenderer.invoke('voice:transcribe', payload),
  createRealtimeCall: payload => ipcRenderer.invoke('realtime:create-call', payload),
  reportRealtimeStatus: status => ipcRenderer.send('realtime:status', status),
  getSkills: () => ipcRenderer.invoke('skills:get'),
  runSkill: (skillId, input) => ipcRenderer.invoke('skills:run', { skillId, input }),
  runTool: toolId => ipcRenderer.invoke('tool:run', toolId),
  listApps: () => ipcRenderer.invoke('apps:list'),
  addApp: () => ipcRenderer.invoke('apps:add'),
  removeApp: appId => ipcRenderer.invoke('apps:remove', appId),
  launchApp: appId => ipcRenderer.invoke('apps:launch', appId),
  searchWeb: query => ipcRenderer.invoke('web:search', query),
  scheduleReminder: payload => ipcRenderer.invoke('reminder:schedule', payload),
  minimize: () => ipcRenderer.send('window:minimize'),
  close: () => ipcRenderer.send('window:close'),
  getWindowMode: () => ipcRenderer.invoke('window:get-mode'),
  setWindowMode: mode => ipcRenderer.invoke('window:set-mode', mode),
  restoreFullWindow: () => ipcRenderer.invoke('window:restore-full'),
  setClickThrough: enabled => ipcRenderer.invoke('window:set-click-through', enabled),
  getWindowDragState: () => ipcRenderer.invoke('window:drag-state'),
  moveWindowTo: position => ipcRenderer.invoke('window:move-to', position),
  reportCompanionRuntime: status => ipcRenderer.send('companion:runtime-status', status),
  onInteractionRestored: callback => ipcRenderer.on('window:interaction-restored', callback),
  onWindowModeChanged: callback => ipcRenderer.on('window:mode-changed', (_event, payload) => callback(payload)),
  onProactiveMessage: callback => ipcRenderer.on('proactive:message', callback),
  onCompanionAction: callback => ipcRenderer.on('companion:action', callback),
  onCompanionUpdated: callback => ipcRenderer.on('companion:updated', callback)
  ,onEnvironmentChanged: callback => ipcRenderer.on('environment:changed', (_event, payload) => callback(payload)),
  onFocusUpdated: callback => ipcRenderer.on('focus:updated', (_event, payload) => callback(payload)),
  onLocalAiStatus: callback => ipcRenderer.on('local-ai:status', (_event, payload) => callback(payload)),
  onModelDownloadStatus: callback => ipcRenderer.on('model-download:status', (_event, payload) => callback(payload)),
  onChatStreamEvent: callback => ipcRenderer.on('chat:stream-event', (_event, payload) => callback(payload)),
  onScenarioUpdated: callback => ipcRenderer.on('scenario:updated', (_event, payload) => callback(payload))
});
